// Copyright © Unbroken AB
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#pragma once

namespace NMib::NBuildSystem
{
	extern CPropertyKeyReference const gc_ConstKey_Architecture;
	extern CPropertyKeyReference const gc_ConstKey_ExcludeFiles;
	extern CPropertyKeyReference const gc_ConstKey_FullConfiguration;
	extern CPropertyKeyReference const gc_ConstKey_MalterlibRepositoryEditor;
	extern CPropertyKeyReference const gc_ConstKey_MalterlibRepositoryEditorSequential;
	extern CPropertyKeyReference const gc_ConstKey_MalterlibRepositoryEditorSleep;
	extern CPropertyKeyReference const gc_ConstKey_MalterlibRepositoryEditorWorkingDir;
	extern CPropertyKeyReference const gc_ConstKey_PerforceRoot;
	extern CPropertyKeyReference const gc_ConstKey_Platform;
	extern CPropertyKeyReference const gc_ConstKey_Disabled;
	extern CPropertyKeyReference const gc_ConstKey_HiddenGroup;
	extern CPropertyKeyReference const gc_ConstKey_MToolVersion;
	extern CPropertyKeyReference const gc_ConstKey_Generator;
	extern CPropertyKeyReference const gc_ConstKey_GeneratorFamily;
	extern CPropertyKeyReference const gc_ConstKey_BuildSystemBasePath;
	extern CPropertyKeyReference const gc_ConstKey_BuildSystemOutputDir;
	extern CPropertyKeyReference const gc_ConstKey_BuildSystemFile;
	extern CPropertyKeyReference const gc_ConstKey_BuildSystemName;
	extern CPropertyKeyReference const gc_ConstKey_HostPlatform;
	extern CPropertyKeyReference const gc_ConstKey_HostPlatformFamily;
	extern CPropertyKeyReference const gc_ConstKey_HostArchitecture;
	extern CPropertyKeyReference const gc_ConstKey_HostSystemInfo;
	extern CPropertyKeyReference const gc_ConstKey_Configuration;
	extern CPropertyKeyReference const gc_ConstKey_AllRepositories;

	extern CPropertyKeyReference const gc_ConstKey_Builtin_GeneratedFiles;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_SourceFiles;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_BuildSystemSourceAbsolute;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_BuildSystemSource;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_GeneratorStateFile;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_BasePathAbsolute;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_MToolExe;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_MalterlibExe;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_BasePathRelativeProject;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_GeneratedBuildSystemDir;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_BasePath;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_IntermediateDirectory;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_OutputDirectory;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_ProjectPath;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_Inherit;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_SourceFileName;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_CMakeRoot;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_ReadFile;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_FileExists;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_LinkExists;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_ResolveSymbolicLink;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_DirectoryExists;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_FileOrDirectoryExists;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_FindFilesIn;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_FindDirectoriesIn;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_FindFilesRecursiveIn;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_FindDirectoriesRecursiveIn;

	extern CPropertyKeyReference const gc_ConstKey_Builtin_Output;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_Input;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_Flags;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_Dollar;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_RspFile;
	extern CPropertyKeyReference const gc_ConstKey_Builtin_VisualStudioRoot;

	extern CPropertyKeyReference const gc_ConstKey_This_Identity;
	extern CPropertyKeyReference const gc_ConstKey_This_IdentityAsAbsolutePath;
	extern CPropertyKeyReference const gc_ConstKey_This_IdentityPath;
	extern CPropertyKeyReference const gc_ConstKey_This_EntityPath;
	extern CPropertyKeyReference const gc_ConstKey_This_Type;

	extern CPropertyKeyReference const gc_ConstKey_Compile_AllowNonExisting;
	extern CPropertyKeyReference const gc_ConstKey_Compile_Custom_CommandLine;
	extern CPropertyKeyReference const gc_ConstKey_Compile_Custom_Inputs;
	extern CPropertyKeyReference const gc_ConstKey_Compile_Custom_Outputs;
	extern CPropertyKeyReference const gc_ConstKey_Compile_Custom_WorkingDirectory;
	extern CPropertyKeyReference const gc_ConstKey_Compile_Disabled;
	extern CPropertyKeyReference const gc_ConstKey_Compile_GenericCompileType;
	extern CPropertyKeyReference const gc_ConstKey_Compile_InitEarly;
	extern CPropertyKeyReference const gc_ConstKey_Compile_PrecompilePrefixHeader;
	extern CPropertyKeyReference const gc_ConstKey_Compile_XInternalPrecompiledHeaderOutputFile;
	extern CPropertyKeyReference const gc_ConstKey_Compile_PrefixHeader;
	extern CPropertyKeyReference const gc_ConstKey_Compile_Type;
	extern CPropertyKeyReference const gc_ConstKey_Compile_SearchPath;
	extern CPropertyKeyReference const gc_ConstKey_Compile_SystemSearchPath;
	extern CPropertyKeyReference const gc_ConstKey_Compile_PreprocessorDefines;
	extern CPropertyKeyReference const gc_ConstKey_Compile_Custom_Message;
	extern CPropertyKeyReference const gc_ConstKey_Compile_TabWidth;
	extern CPropertyKeyReference const gc_ConstKey_Compile_IndentWidth;
	extern CPropertyKeyReference const gc_ConstKey_Compile_UsesTabs;

	extern CPropertyKeyReference const gc_ConstKey_CreateTemplate_Name;

	extern CPropertyKeyReference const gc_ConstKey_Dependency_Indirect;
	extern CPropertyKeyReference const gc_ConstKey_Dependency_IndirectOrdered;
	extern CPropertyKeyReference const gc_ConstKey_Dependency_IndirectEvaluated;
	extern CPropertyKeyReference const gc_ConstKey_Dependency_IndirectOrderedEvaluated;
	extern CPropertyKeyReference const gc_ConstKey_Dependency_TargetPropertyPath;
	extern CPropertyKeyReference const gc_ConstKey_Dependency_Link;
	extern CPropertyKeyReference const gc_ConstKey_Dependency_Type;
	extern CPropertyKeyReference const gc_ConstKey_Dependency_Name;
	extern CPropertyKeyReference const gc_ConstKey_Dependency_Target;
	extern CPropertyKeyReference const gc_ConstKey_Dependency_TargetProperties;
	extern CPropertyKeyReference const gc_ConstKey_Dependency_ObjectLibrary;

	extern CPropertyKeyReference const gc_ConstKey_GenerateFile_BeforeImports;
	extern CPropertyKeyReference const gc_ConstKey_GenerateFile_Contents;
	extern CPropertyKeyReference const gc_ConstKey_GenerateFile_Executable;
	extern CPropertyKeyReference const gc_ConstKey_GenerateFile_Group;
	extern CPropertyKeyReference const gc_ConstKey_GenerateFile_KeepGeneratedFile;
	extern CPropertyKeyReference const gc_ConstKey_GenerateFile_Name;
	extern CPropertyKeyReference const gc_ConstKey_GenerateFile_NoDateCheck;
	extern CPropertyKeyReference const gc_ConstKey_GenerateFile_Symlink;
	extern CPropertyKeyReference const gc_ConstKey_GenerateFile_SymlinkBasePath;
	extern CPropertyKeyReference const gc_ConstKey_GenerateFile_SymlinkDirectory;
	extern CPropertyKeyReference const gc_ConstKey_GenerateFile_UnicodeBOM;
	extern CPropertyKeyReference const gc_ConstKey_GenerateFile_UnixLineEnds;
	extern CPropertyKeyReference const gc_ConstKey_GenerateFile_UTF16;

	extern CPropertyKeyReference const gc_ConstKey_GeneratorSetting_Workspace;
	extern CPropertyKeyReference const gc_ConstKey_GeneratorSetting_Target;
	extern CPropertyKeyReference const gc_ConstKey_GeneratorSetting_TargetValidateSettings;
	extern CPropertyKeyReference const gc_ConstKey_GeneratorSetting_CompileValidateSettings;
	extern CPropertyKeyReference const gc_ConstKey_GeneratorSetting_Dependency;
	extern CPropertyKeyReference const gc_ConstKey_GeneratorSetting_Compile;

	extern CPropertyKeyReference const gc_ConstKey_GeneratorSetting_DefinedProperties;
	extern CPropertyKeyReference const gc_ConstKey_GeneratorSetting_IsFile;
	extern CPropertyKeyReference const gc_ConstKey_GeneratorSetting_Xcode_TargetType;

	extern CPropertyKeyReference const gc_ConstKey_Group_HideTargets;;

	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_AlwaysFullRebuild;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_CacheDirectory;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_CacheDuplicateLines;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_CacheExcludePatterns;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_CacheExcludeDependenciesPatterns;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_CacheIgnoreInputs;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_CacheReplaceContents;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_CCompiler;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_CCompilerTarget;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_CExternalToolChain;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_Config;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_CxxCompiler;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_CxxCompilerTarget;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_OutputFilesParseTerminators;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_CxxExternalToolChain;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_DiffHash;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_ForceCrossCompile;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_Environment;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_ExcludeFromHash;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_DisableIncludeReplace;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_FullRebuildVersion;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_IncludeInHash;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_IntermediateName;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_Languages;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_Path;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_Projects;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_ReplacePrefixes;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_SysRoot;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_SystemName;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_SystemProcessor;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_UpdateCache;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_Variables;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_VariablesWithPaths;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_Verbose;
	extern CPropertyKeyReference const gc_ConstKey_Import_CMake_VerboseHash;
	extern CPropertyKeyReference const gc_ConstKey_Import_SharedTempDirectory;
	extern CPropertyKeyReference const gc_ConstKey_Import_TempDirectory;

	extern CPropertyKeyReference const gc_ConstKey_Repository_AdditionalConfigFiles;
	extern CPropertyKeyReference const gc_ConstKey_Repository_ConfigFile;
	extern CPropertyKeyReference const gc_ConstKey_Repository_DefaultBranch;
	extern CPropertyKeyReference const gc_ConstKey_Repository_DefaultUpstreamBranch;
	extern CPropertyKeyReference const gc_ConstKey_Repository_ExcludeFromSeen;
	extern CPropertyKeyReference const gc_ConstKey_Repository_Location;
	extern CPropertyKeyReference const gc_ConstKey_Repository_NoPushRemotes;
	extern CPropertyKeyReference const gc_ConstKey_Repository_ProtectedBranches;
	extern CPropertyKeyReference const gc_ConstKey_Repository_ProtectedTags;
	extern CPropertyKeyReference const gc_ConstKey_Repository_Remotes;
	extern CPropertyKeyReference const gc_ConstKey_Repository_StateFile;
	extern CPropertyKeyReference const gc_ConstKey_Repository_Submodule;
	extern CPropertyKeyReference const gc_ConstKey_Repository_SubmoduleName;
	extern CPropertyKeyReference const gc_ConstKey_Repository_Tags;
	extern CPropertyKeyReference const gc_ConstKey_Repository_Type;
	extern CPropertyKeyReference const gc_ConstKey_Repository_UpdateSubmodules;
	extern CPropertyKeyReference const gc_ConstKey_Repository_URL;
	extern CPropertyKeyReference const gc_ConstKey_Repository_UserEmail;
	extern CPropertyKeyReference const gc_ConstKey_Repository_UserName;
	extern CPropertyKeyReference const gc_ConstKey_Repository_LfsReleaseStore;
	extern CPropertyKeyReference const gc_ConstKey_Repository_TagPreviousOnForcePush;
	extern CPropertyKeyReference const gc_ConstKey_Repository_ExtraFetchSpecs;
	extern CPropertyKeyReference const gc_ConstKey_Repository_Policy;
	extern CPropertyKeyReference const gc_ConstKey_Repository_ReleasePackage;
	extern CPropertyKeyReference const gc_ConstKey_Repository_ApplyPolicy;
	extern CPropertyKeyReference const gc_ConstKey_Repository_ApplyPolicyPretend;
	extern CPropertyKeyReference const gc_ConstKey_Repository_BootstrapSource;
	extern CPropertyKeyReference const gc_ConstKey_Repository_GitIgnoreType;
	extern CPropertyKeyReference const gc_ConstKey_Repository_License;
	extern CPropertyKeyReference const gc_ConstKey_Repository_CheckLicense;
	extern CPropertyKeyReference const gc_ConstKey_Repository_HookHelperFiles;
	extern CPropertyKeyReference const gc_ConstKey_Repository_Hooks;
	extern CPropertyKeyReference const gc_ConstKey_Repository_RepoCommit;

	extern CPropertyKeyReference const gc_ConstKey_Target_ClCompileSuffix;
	extern CPropertyKeyReference const gc_ConstKey_Target_DependencyFile;
	extern CPropertyKeyReference const gc_ConstKey_Target_DependencyInjectionGroups;
	extern CPropertyKeyReference const gc_ConstKey_Target_Disabled;
	extern CPropertyKeyReference const gc_ConstKey_Target_EnableLinkerGroups;
	extern CPropertyKeyReference const gc_ConstKey_Target_ExportScriptEnvironmentContents;
	extern CPropertyKeyReference const gc_ConstKey_Target_ExternalDependencies;
	extern CPropertyKeyReference const gc_ConstKey_Target_ExtraGroups;
	extern CPropertyKeyReference const gc_ConstKey_Target_InjectedExtraGroups;
	extern CPropertyKeyReference const gc_ConstKey_Target_FileExtension;
	extern CPropertyKeyReference const gc_ConstKey_Target_FileName;
	extern CPropertyKeyReference const gc_ConstKey_Target_FollowIndirectDependencies;
	extern CPropertyKeyReference const gc_ConstKey_Target_GenerateScheme;
	extern CPropertyKeyReference const gc_ConstKey_Target_Group;
	extern CPropertyKeyReference const gc_ConstKey_Target_LinkerGroup;
	extern CPropertyKeyReference const gc_ConstKey_Target_Name;
	extern CPropertyKeyReference const gc_ConstKey_Target_ObjectLibrary;
	extern CPropertyKeyReference const gc_ConstKey_Target_OutputDirectory;
	extern CPropertyKeyReference const gc_ConstKey_Target_PlatformVersion;
	extern CPropertyKeyReference const gc_ConstKey_Target_TargetFrameworkVersion;
	extern CPropertyKeyReference const gc_ConstKey_Target_VisualStudioPlatform;
	extern CPropertyKeyReference const gc_ConstKey_Target_DependenciesNames;
	extern CPropertyKeyReference const gc_ConstKey_Target_Dependencies;
	extern CPropertyKeyReference const gc_ConstKey_Target_DependencyTargets;
	extern CPropertyKeyReference const gc_ConstKey_Target_Type;
	extern CPropertyKeyReference const gc_ConstKey_Target_Language;
	extern CPropertyKeyReference const gc_ConstKey_Target_IntermediateDirectory;
	extern CPropertyKeyReference const gc_ConstKey_Target_PostBuildScriptOutputs;
	extern CPropertyKeyReference const gc_ConstKey_Target_PostBuildScriptInputs;
	extern CPropertyKeyReference const gc_ConstKey_Target_PreBuildScriptOutputs;
	extern CPropertyKeyReference const gc_ConstKey_Target_PreBuildScriptInputs;
	extern CPropertyKeyReference const gc_ConstKey_Target_LinkWithLibraries;
	extern CPropertyKeyReference const gc_ConstKey_Target_AllFiles;
	extern CPropertyKeyReference const gc_ConstKey_Target_CompileCommandsFile;

	extern CPropertyKeyReference const gc_ConstKey_Workspace_Enabled;
	extern CPropertyKeyReference const gc_ConstKey_Workspace_ExtraGroups;
	extern CPropertyKeyReference const gc_ConstKey_Workspace_Name;
	extern CPropertyKeyReference const gc_ConstKey_Workspace_XcodeNewBuildSystem;
	extern CPropertyKeyReference const gc_ConstKey_Workspace_IntermediateDirectory;
	extern CPropertyKeyReference const gc_ConstKey_Workspace_OutputDirectory;
	extern CPropertyKeyReference const gc_ConstKey_Workspace_AllTargets;

	extern CPropertyKeyReference const gc_ConstKeys_FullEval[EPropertyType_Max];

	void fg_CacheConstantKeys(CStringCache &o_StringCache);
}

