// Copyright © 2022 Favro Holding AB
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Malterlib_BuildSystem_ConstantStrings.h"

// To find candidates for sharing const strings:
// ag "gc_Str<" | grep 'gc_Str<' | grep -v -e Malterlib_BuildSystem_ConstantKeys.cpp -e Malterlib_BuildSystem_ConstantStrings.hpp | awk -F'gc_Str<"' '{print $2}' | awk -F'">' '{print $1}' | sort | uniq -cd

namespace NMib::NBuildSystem
{
	constexpr CStringAndHash const gc_ConstString_Accessors = gc_Str<"Accessors">;
	constexpr CStringAndHash const gc_ConstString_any = gc_Str<"any">;
	constexpr CStringAndHash const gc_ConstString_AppendExpression = gc_Str<"AppendExpression">;
	constexpr CStringAndHash const gc_ConstString_Architecture = gc_Str<"Architecture">;
	constexpr CStringAndHash const gc_ConstString_Argument = gc_Str<"Argument">;
	constexpr CStringAndHash const gc_ConstString_binary = gc_Str<"binary">;
	constexpr CStringAndHash const gc_ConstString_BinaryOperator = gc_Str<"BinaryOperator">;
	constexpr CStringAndHash const gc_ConstString_bool = gc_Str<"bool">;
	constexpr CStringAndHash const gc_ConstString_BuildSystemToken = gc_Str<"BuildSystemToken">;
	constexpr CStringAndHash const gc_ConstString_Column = gc_Str<"Column">;
	constexpr CStringAndHash const gc_ConstString_Conditional = gc_Str<"Conditional">;
	constexpr CStringAndHash const gc_ConstString_Configuration = gc_Str<"Configuration">;
	constexpr CStringAndHash const gc_ConstString_date = gc_Str<"date">;
	constexpr CStringAndHash const gc_ConstString_DefaultBranch = gc_Str<"DefaultBranch">;
	constexpr CStringAndHash const gc_ConstString_DefaultType = gc_Str<"DefaultType">;
	constexpr CStringAndHash const gc_ConstString_DefaultValue = gc_Str<"DefaultValue">;
	constexpr CStringAndHash const gc_ConstString_Define = gc_Str<"Define">;
	constexpr CStringAndHash const gc_ConstString_Disabled = gc_Str<"Disabled">;
	constexpr CStringAndHash const gc_ConstString_Ellipsis = gc_Str<"Ellipsis">;
	constexpr CStr const gc_ConstString_Empty = CStr();
	constexpr CStringAndHash const gc_ConstString_EntityType = gc_Str<"EntityType">;
	constexpr CStringAndHash const gc_ConstString_ERROR = gc_Str<"ERROR">;
	constexpr CStringAndHash const gc_ConstString_EvalString = gc_Str<"EvalString">;
	constexpr CStringAndHash const gc_ConstString_Expression = gc_Str<"Expression">;
	constexpr CStringAndHash const gc_ConstString_File = gc_Str<"File">;
	constexpr CStringAndHash const gc_ConstString_float = gc_Str<"float">;
	constexpr CStringAndHash const gc_ConstString_FullEval = gc_Str<"FullEval">;
	constexpr CStringAndHash const gc_ConstString_Function = gc_Str<"Function">;
	constexpr CStringAndHash const gc_ConstString_FunctionType = gc_Str<"FunctionType">;
	constexpr CStringAndHash const gc_ConstString_Group = gc_Str<"Group">;
	constexpr CStringAndHash const gc_ConstStringDynamic_DPlatform = gc_Str<DMibStringize(DPlatform)>;
	constexpr CStringAndHash const gc_ConstStringDynamic_DPlatformFamily = gc_Str<DMibStringize(DPlatformFamily)>;
	constexpr CStringAndHash const gc_ConstStringDynamic_DArchitecture = gc_Str<DMibStringize(DArchitecture)>;
	constexpr CStringAndHash const gc_ConstString_identifier = gc_Str<"identifier">;
	constexpr CStringAndHash const gc_ConstString_Identifier = gc_Str<"Identifier">;
	constexpr CStringAndHash const gc_ConstString_IdentifierReference = gc_Str<"IdentifierReference">;
	constexpr CStringAndHash const gc_ConstString_Identity = gc_Str<"Identity">;
	constexpr CStringAndHash const gc_ConstString_IdentityAsAbsolutePath = gc_Str<"IdentityAsAbsolutePath">;
	constexpr CStringAndHash const gc_ConstString_IdentityPath = gc_Str<"IdentityPath">;
	constexpr CStringAndHash const gc_ConstString_EntityPath = gc_Str<"EntityPath">;
	constexpr CStringAndHash const gc_ConstString_InnerType = gc_Str<"InnerType">;
	constexpr CStringAndHash const gc_ConstString_int = gc_Str<"int">;
	constexpr CStringAndHash const gc_ConstString_JSONAccessor = gc_Str<"JSONAccessor">;
	constexpr CStringAndHash const gc_ConstString_KeyLogicalOperator = gc_Str<"KeyLogicalOperator">;
	constexpr CStringAndHash const gc_ConstString_KeyPrefixOperator = gc_Str<"KeyPrefixOperator">;
	constexpr CStringAndHash const gc_ConstString_Namespace = gc_Str<"Namespace">;
	constexpr CStringAndHash const gc_ConstString_Left = gc_Str<"Left">;
	constexpr CStringAndHash const gc_ConstString_Legacy = gc_Str<"Legacy">;
	constexpr CStringAndHash const gc_ConstString_Line = gc_Str<"Line">;
	constexpr CStringAndHash const gc_ConstString_Message = gc_Str<"Message">;
	constexpr CStringAndHash const gc_ConstString_Name = gc_Str<"Name">;
	constexpr CStringAndHash const gc_ConstString_OneOf = gc_Str<"OneOf">;
	constexpr CStringAndHash const gc_ConstString_OneOfList = gc_Str<"OneOfList">;
	constexpr CStringAndHash const gc_ConstString_Operator = gc_Str<"Operator">;
	constexpr CStringAndHash const gc_ConstString_Optional = gc_Str<"Optional">;
	constexpr CStringAndHash const gc_ConstString_Param = gc_Str<"Param">;
	constexpr CStringAndHash const gc_ConstString_Parameters = gc_Str<"Parameters">;
	constexpr CStringAndHash const gc_ConstString_Params = gc_Str<"Params">;
	constexpr CStringAndHash const gc_ConstString_Paren = gc_Str<"Paren">;
	constexpr CStringAndHash const gc_ConstString_Platform = gc_Str<"Platform">;
	constexpr CStringAndHash const gc_ConstString_PostFunction = gc_Str<"PostFunction">;
	constexpr CStringAndHash const gc_ConstString_PrefixOperator = gc_Str<"PrefixOperator">;
	constexpr CStringAndHash const gc_ConstString_PropertyType = gc_Str<"PropertyType">;
	constexpr CStringAndHash const gc_ConstString_ReturnType = gc_Str<"ReturnType">;
	constexpr CStringAndHash const gc_ConstString_Right = gc_Str<"Right">;
	constexpr CStringAndHash const gc_ConstString_RootValue = gc_Str<"RootValue">;
	constexpr CStringAndHash const gc_ConstString_String = gc_Str<"String">;
	constexpr CStringAndHash const gc_ConstString_string = gc_Str<"string">;
	constexpr CStringAndHash const gc_ConstString_Subscript = gc_Str<"Subscript">;
	constexpr CStringAndHash const gc_ConstString_Symbol_AccessObject = gc_Str<"->">;
	constexpr CStringAndHash const gc_ConstString_Symbol_AppendObject = gc_Str<"<<">;
	constexpr CStringAndHash const gc_ConstString_Symbol_AppendObjectNoQuote = gc_Str<TCStrConstData("<<", EJSONStringType_NoQuote)>;
	constexpr CStringAndHash const gc_ConstString_Symbol_BitwiseNot = gc_Str<"~">;
	constexpr CStringAndHash const gc_ConstString_Symbol_ConfigurationPrefix = gc_Str<"*">;
	constexpr CStringAndHash const gc_ConstString_Symbol_Ellipsis = gc_Str<"...">;
	constexpr CStringAndHash const gc_ConstString_Symbol_EllipsisNoQuote = gc_Str<TCStrConstData("...", EJSONStringType_NoQuote)>;
	constexpr CStringAndHash const gc_ConstString_Symbol_EntityPrefix = gc_Str<"%">;
	constexpr CStringAndHash const gc_ConstString_Symbol_LogicalAnd = gc_Str<"&">;
	constexpr CStringAndHash const gc_ConstString_Symbol_LogicalNot = gc_Str<"!">;
	constexpr CStringAndHash const gc_ConstString_Symbol_LogicalNotNot = gc_Str<"!!">;
	constexpr CStringAndHash const gc_ConstString_Symbol_LogicalOr = gc_Str<"|">;
	constexpr CStringAndHash const gc_ConstString_Symbol_MakeReference = gc_Str<"&">;
	constexpr CStringAndHash const gc_ConstString_Symbol_OperatorAdd = gc_Str<"+">;
	constexpr CStringAndHash const gc_ConstString_Symbol_OperatorAnd = gc_Str<"&&">;
	constexpr CStringAndHash const gc_ConstString_Symbol_OperatorAppend = gc_Str<"=+">;
	constexpr CStringAndHash const gc_ConstString_Symbol_OperatorBitwiseAnd = gc_Str<"&">;
	constexpr CStringAndHash const gc_ConstString_Symbol_OperatorBitwiseLeftShift = gc_Str<"<<">;
	constexpr CStringAndHash const gc_ConstString_Symbol_OperatorBitwiseOr = gc_Str<"|">;
	constexpr CStringAndHash const gc_ConstString_Symbol_OperatorBitwiseRightShift = gc_Str<">>">;
	constexpr CStringAndHash const gc_ConstString_Symbol_OperatorBitwiseXor = gc_Str<"^">;
	constexpr CStringAndHash const gc_ConstString_Symbol_OperatorDivide = gc_Str<"/">;
	constexpr CStringAndHash const gc_ConstString_Symbol_OperatorEqual = gc_Str<"==">;
	constexpr CStringAndHash const gc_ConstString_Symbol_OperatorGreaterThan = gc_Str<">">;
	constexpr CStringAndHash const gc_ConstString_Symbol_OperatorGreaterThanEqual = gc_Str<">=">;
	constexpr CStringAndHash const gc_ConstString_Symbol_OperatorLessThan = gc_Str<"<">;
	constexpr CStringAndHash const gc_ConstString_Symbol_OperatorLessThanEqual = gc_Str<"<=">;
	constexpr CStringAndHash const gc_ConstString_Symbol_OperatorMatchEqual = gc_Str<"<==>">;
	constexpr CStringAndHash const gc_ConstString_Symbol_OperatorMatchNotEqual = gc_Str<"<!=>">;
	constexpr CStringAndHash const gc_ConstString_Symbol_OperatorModulus = gc_Str<"%">;
	constexpr CStringAndHash const gc_ConstString_Symbol_OperatorMultiply = gc_Str<"*">;
	constexpr CStringAndHash const gc_ConstString_Symbol_OperatorNotEqual = gc_Str<"!=">;
	constexpr CStringAndHash const gc_ConstString_Symbol_OperatorOr = gc_Str<"||">;
	constexpr CStringAndHash const gc_ConstString_Symbol_OperatorNullishCoalescing = gc_Str<"??">;
	constexpr CStringAndHash const gc_ConstString_Symbol_OperatorPrepend = gc_Str<"+=">;
	constexpr CStringAndHash const gc_ConstString_Symbol_OperatorSubtract = gc_Str<"-">;
	constexpr CStringAndHash const gc_ConstString_Symbol_Optional = gc_Str<"?">;
	constexpr CStringAndHash const gc_ConstString_Symbol_PragmaPrefix = gc_Str<"#">;
	constexpr CStringAndHash const gc_ConstString_namespace = gc_Str<"namespace">;
	constexpr CStringAndHash const gc_ConstString_Target = gc_Str<"Target">;
	constexpr CStringAndHash const gc_ConstString_Ternary = gc_Str<"Ternary">;
	constexpr CStringAndHash const gc_ConstString_Type = gc_Str<"Type">;
	constexpr CStringAndHash const gc_ConstString_TypeDefaulted = gc_Str<"TypeDefaulted">;
	constexpr CStringAndHash const gc_ConstString_TypeName = gc_Str<"TypeName">;
	constexpr CStringAndHash const gc_ConstString_URL = gc_Str<"URL">;
	constexpr CStringAndHash const gc_ConstString_Value = gc_Str<"Value">;
	constexpr CStringAndHash const gc_ConstString_void = gc_Str<"void">;
	constexpr CStringAndHash const gc_ConstString_WildcardString = gc_Str<"WildcardString">;
	constexpr CStringAndHash const gc_ConstString_Write = gc_Str<"Write">;
	constexpr CStringAndHash const gc_ConstString_VisualStudioRoot = gc_Str<"VisualStudioRoot">;
	constexpr CStringAndHash const gc_ConstString_XInternalPrecompiledHeaderOutputFile = gc_Str<"XInternalPrecompiledHeaderOutputFile">;
	constexpr CStringAndHash const gc_ConstString_Replace = gc_Str<"Replace">;
	constexpr CStringAndHash const gc_ConstString_Find = gc_Str<"Find">;
	constexpr CStringAndHash const gc_ConstString_MakeAbsolute = gc_Str<"MakeAbsolute">;
	constexpr CStringAndHash const gc_ConstString_Error = gc_Str<"Error">;
	constexpr CStringAndHash const gc_ConstString_Root = gc_Str<"Root">;
	constexpr CStringAndHash const gc_ConstString_Workspace = gc_Str<"Workspace">;
	constexpr CStringAndHash const gc_ConstString_Dependency = gc_Str<"Dependency">;
	constexpr CStringAndHash const gc_ConstString_GeneratorSetting = gc_Str<"GeneratorSetting">;
	constexpr CStringAndHash const gc_ConstString_GenerateFile = gc_Str<"GenerateFile">;
	constexpr CStringAndHash const gc_ConstString_Import = gc_Str<"Import">;
	constexpr CStringAndHash const gc_ConstString_Repository = gc_Str<"Repository">;
	constexpr CStringAndHash const gc_ConstString_CreateTemplate = gc_Str<"CreateTemplate">;
	constexpr CStringAndHash const gc_ConstString_Property = gc_Str<"Property">;
	constexpr CStringAndHash const gc_ConstString_Compile = gc_Str<"Compile">;
	constexpr CStringAndHash const gc_ConstString_this = gc_Str<"this">;
	constexpr CStringAndHash const gc_ConstString_Builtin = gc_Str<"Builtin">;
	constexpr CStringAndHash const gc_ConstString_undefined = gc_Str<"undefined">;
	constexpr CStringAndHash const gc_ConstString_3FFADB4E_9D9D_4CD7_8FA8_539C6ABF79BA = gc_Str<"3FFADB4E-9D9D-4CD7-8FA8-539C6ABF79BA">;
	constexpr CStringAndHash const gc_ConstString_PBXFileReference = gc_Str<"PBXFileReference">;
	constexpr CStringAndHash const gc_ConstString_Positions = gc_Str<"Positions">;
	constexpr CStringAndHash const gc_ConstString_lastKnownFileType = gc_Str<"lastKnownFileType">;
	constexpr CStringAndHash const gc_ConstString_explicitFileType = gc_Str<"explicitFileType">;
	constexpr CStringAndHash const gc_ConstString_fileEncoding = gc_Str<"fileEncoding">;
	constexpr CStringAndHash const gc_ConstString_tabWidth = gc_Str<"tabWidth">;
	constexpr CStringAndHash const gc_ConstString_usesTabs = gc_Str<"usesTabs">;
	constexpr CStringAndHash const gc_ConstString_indentWidth = gc_Str<"indentWidth">;
	constexpr CStringAndHash const gc_ConstString_XCConfigs = gc_Str<"XCConfigs">;
	constexpr CStringAndHash const gc_ConstString_VSSettings = gc_Str<"VSSettings">;
	constexpr CStringAndHash const gc_ConstString_YES = gc_Str<"YES">;
	constexpr CStringAndHash const gc_ConstString_NO = gc_Str<"NO">;
	constexpr CStringAndHash const gc_ConstString_Flags = gc_Str<"Flags">;
	constexpr CStringAndHash const gc_ConstString_ProductType = gc_Str<"ProductType">;
	constexpr CStringAndHash const gc_ConstString_Entity = gc_Str<"Entity">;
	constexpr CStringAndHash const gc_ConstString_Symbol_Cpp = gc_Str<"C++">;
	constexpr CStringAndHash const gc_ConstString_Symbol_CppManaged = gc_Str<"C++Managed">;
	constexpr CStringAndHash const gc_ConstString_Symbol_ObjCpp = gc_Str<"ObjC++">;
	constexpr CStringAndHash const gc_ConstString_PostBuildScript = gc_Str<"PostBuildScript">;
	constexpr CStringAndHash const gc_ConstString_ToolBuildScript = gc_Str<"ToolBuildScript">;
	constexpr CStringAndHash const gc_ConstString_ToolBuildScriptInputs = gc_Str<"ToolBuildScriptInputs">;
	constexpr CStringAndHash const gc_ConstString_ToolBuildScriptOutputs = gc_Str<"ToolBuildScriptOutputs">;
	constexpr CStringAndHash const gc_ConstString_PreBuildScript = gc_Str<"PreBuildScript">;
	constexpr CStringAndHash const gc_ConstString_GCC_PRECOMPILE_PREFIX_HEADER = gc_Str<"GCC_PRECOMPILE_PREFIX_HEADER">;
	constexpr CStringAndHash const gc_ConstString_GCC_PREFIX_HEADER = gc_Str<"GCC_PREFIX_HEADER">;
	constexpr CStringAndHash const gc_ConstString_C = gc_Str<"C">;
	constexpr CStringAndHash const gc_ConstString_ObjC = gc_Str<"ObjC">;
	constexpr CStringAndHash const gc_ConstString_Assembler = gc_Str<"Assembler">;
	constexpr CStringAndHash const gc_ConstString_MOC_OUTPUT_PATTERN = gc_Str<"MOC_OUTPUT_PATTERN">;
	constexpr CStringAndHash const gc_ConstString_FilesExcludedFromCompile = gc_Str<"FilesExcludedFromCompile">;
	constexpr CStringAndHash const gc_ConstString_true = gc_Str<"true">;
	constexpr CStringAndHash const gc_ConstString_false = gc_Str<"false">;
	constexpr CStringAndHash const gc_ConstString_null = gc_Str<"null">;
	constexpr CStringAndHash const gc_ConstString_define = gc_Str<"define">;
	constexpr CStringAndHash const gc_ConstString_function = gc_Str<"function">;
	constexpr CStringAndHash const gc_ConstString_type = gc_Str<"type">;
	constexpr CStringAndHash const gc_ConstString_one_of = gc_Str<"one_of">;
	constexpr CStringAndHash const gc_ConstString_nolink = gc_Str<"nolink">;
	constexpr CStringAndHash const gc_ConstString_PRODUCT_NAME = gc_Str<"PRODUCT_NAME">;
	constexpr CStringAndHash const gc_ConstString_EXECUTABLE_EXTENSION = gc_Str<"EXECUTABLE_EXTENSION">;
	constexpr CStringAndHash const gc_ConstString_BUILT_PRODUCTS_DIR = gc_Str<"BUILT_PRODUCTS_DIR">;
	constexpr CStringAndHash const gc_ConstString_CONFIGURATION_BUILD_DIR = gc_Str<"CONFIGURATION_BUILD_DIR">;
	constexpr CStringAndHash const gc_ConstString_NATIVE_ARCH_ACTUAL = gc_Str<"NATIVE_ARCH_ACTUAL">;
	constexpr CStringAndHash const gc_ConstString_BUILD_DIR = gc_Str<"BUILD_DIR">;
	constexpr CStringAndHash const gc_ConstString_BUILD_ROOT = gc_Str<"BUILD_ROOT">;
	constexpr CStringAndHash const gc_ConstString_CONFIGURATION_TEMP_DIR = gc_Str<"CONFIGURATION_TEMP_DIR">;
	constexpr CStringAndHash const gc_ConstString_OBJROOT = gc_Str<"OBJROOT">;
	constexpr CStringAndHash const gc_ConstString_PROJECT_DERIVED_FILE_DIR = gc_Str<"PROJECT_DERIVED_FILE_DIR">;
	constexpr CStringAndHash const gc_ConstString_PROJECT_TEMP_DIR = gc_Str<"PROJECT_TEMP_DIR">;
	constexpr CStringAndHash const gc_ConstString_PROJECT_TEMP_ROOT = gc_Str<"PROJECT_TEMP_ROOT">;
	constexpr CStringAndHash const gc_ConstString_SHARED_PRECOMPS_DIR = gc_Str<"SHARED_PRECOMPS_DIR">;
	constexpr CStringAndHash const gc_ConstString_SYMROOT = gc_Str<"SYMROOT">;
	constexpr CStringAndHash const gc_ConstString_TARGET_TEMP_DIR = gc_Str<"TARGET_TEMP_DIR">;
	constexpr CStringAndHash const gc_ConstString_TEMP_FILES_DIR = gc_Str<"TEMP_FILES_DIR">;
	constexpr CStringAndHash const gc_ConstString_TEMP_FILE_DIR = gc_Str<"TEMP_FILE_DIR">;
	constexpr CStringAndHash const gc_ConstString_TEMP_ROOT = gc_Str<"TEMP_ROOT">;
	constexpr CStringAndHash const gc_ConstString_MODULE_CACHE_DIR = gc_Str<"MODULE_CACHE_DIR">;
	constexpr CStringAndHash const gc_ConstString_generatedContainer = gc_Str<"generatedContainer">;
	constexpr CStringAndHash const gc_ConstString_StaticLibrary = gc_Str<"StaticLibrary">;
	constexpr CStringAndHash const gc_ConstString_SharedDynamicLibrary = gc_Str<"SharedDynamicLibrary">;
	constexpr CStringAndHash const gc_ConstString_Custom = gc_Str<"Custom">;
	constexpr CStringAndHash const gc_ConstString_argument = gc_Str<"argument">;
	constexpr CStringAndHash const gc_ConstString_LocalDebuggerCommand = gc_Str<"LocalDebuggerCommand">;
	constexpr CStringAndHash const gc_ConstString_customWorkingDirectory = gc_Str<"customWorkingDirectory">;
	constexpr CStringAndHash const gc_ConstString_CommandLineArgument = gc_Str<"CommandLineArgument">;
	constexpr CStringAndHash const gc_ConstString_LIBRARY_SEARCH_PATHS = gc_Str<"LIBRARY_SEARCH_PATHS">;
	constexpr CStringAndHash const gc_ConstString_OTHER_LDFLAGS = gc_Str<"OTHER_LDFLAGS">;
	constexpr CStringAndHash const gc_ConstString_LDFlagsFirst = gc_Str<"LDFlagsFirst">;
	constexpr CStringAndHash const gc_ConstString_OTHER_LIBTOOLFLAGS = gc_Str<"OTHER_LIBTOOLFLAGS">;
	constexpr CStringAndHash const gc_ConstString_PropertyGroup = gc_Str<"PropertyGroup">;
	constexpr CStringAndHash const gc_ConstString_XInternalCreate = gc_Str<"XInternalCreate">;
	constexpr CStringAndHash const gc_ConstString_CMakeLanguage = gc_Str<"CMakeLanguage">;
	constexpr CStringAndHash const gc_ConstString_MalterlibLanguage = gc_Str<"MalterlibLanguage">;
	constexpr CStringAndHash const gc_ConstString_Match = gc_Str<"Match">;
	constexpr CStringAndHash const gc_ConstString_FilePatterns = gc_Str<"FilePatterns">;
	constexpr CStringAndHash const gc_ConstString_ExcludeFilePatterns = gc_Str<"ExcludeFilePatterns">;
	constexpr CStringAndHash const gc_ConstString_ApplyToPaths = gc_Str<"ApplyToPaths">;
	constexpr CStringAndHash const gc_ConstString_Include = gc_Str<"Include">;
	constexpr CStringAndHash const gc_ConstString_XcodeGeneratorDependencyFiles = gc_Str<"XcodeGeneratorDependencyFiles">;
	constexpr CStringAndHash const gc_ConstString_LfsReleaseStore = gc_Str<"LfsReleaseStore">;

	constexpr CStringAndHash const gc_ConstString_Settings = gc_Str<"Settings">;
	constexpr CStringAndHash const gc_ConstString_17_0 = gc_Str<"17.0">;
	constexpr CStringAndHash const gc_ConstString_And = gc_Str<"And">;
	constexpr CStringAndHash const gc_ConstString_AppendPath = gc_Str<"AppendPath">;
	constexpr CStringAndHash const gc_ConstString_AsBoolean = gc_Str<"AsBoolean">;
	constexpr CStringAndHash const gc_ConstString_AsFloat = gc_Str<"AsFloat">;
	constexpr CStringAndHash const gc_ConstString_AsInteger = gc_Str<"AsInteger">;
	constexpr CStringAndHash const gc_ConstString_AsString = gc_Str<"AsString">;
	constexpr CStringAndHash const gc_ConstString_CMakeIntermediateDirectory{gc_Str<"CMakeIntermediateDirectory">};
	constexpr CStringAndHash const gc_ConstString_Concat = gc_Str<"Concat">;
	constexpr CStringAndHash const gc_ConstString_Condition = gc_Str<"Condition">;
	constexpr CStringAndHash const gc_ConstString_Configurations = gc_Str<"Configurations">;
	constexpr CStringAndHash const gc_ConstString_ContainsListElement = gc_Str<"ContainsListElement">;
	constexpr CStringAndHash const gc_ConstString_Context = gc_Str<"Context">;
	constexpr CStringAndHash const gc_ConstString_DateTime = gc_Str<"DateTime">;
	constexpr CStringAndHash const gc_ConstString_EJSONToString = gc_Str<"EJSONToString">;
	constexpr CStringAndHash const gc_ConstString_EndsWith = gc_Str<"EndsWith">;
	constexpr CStringAndHash const gc_ConstString_Equal = gc_Str<"Equal">;
	constexpr CStringAndHash const gc_ConstString_ErrorWithPositions = gc_Str<"ErrorWithPositions">;
	constexpr CStringAndHash const gc_ConstString_Escape = gc_Str<"Escape">;
	constexpr CStringAndHash const gc_ConstString_EscapeBash = gc_Str<"EscapeBash">;
	constexpr CStringAndHash const gc_ConstString_EscapeHost = gc_Str<"EscapeHost">;
	constexpr CStringAndHash const gc_ConstString_EscapeMSBuild = gc_Str<"EscapeMSBuild">;
	constexpr CStringAndHash const gc_ConstString_EscapeWindows = gc_Str<"EscapeWindows">;
	constexpr CStringAndHash const gc_ConstString_ExcludedFromBuild = gc_Str<"ExcludedFromBuild">;
	constexpr CStringAndHash const gc_ConstString_ExecuteCommand = gc_Str<"ExecuteCommand">;
	constexpr CStringAndHash const gc_ConstString_File_entity = gc_Str<"File entity">;
	constexpr CStringAndHash const gc_ConstString_FindGetLine = gc_Str<"FindGetLine">;
	constexpr CStringAndHash const gc_ConstString_FindNoCase = gc_Str<"FindNoCase">;
	constexpr CStringAndHash const gc_ConstString_ForEach = gc_Str<"ForEach">;
	constexpr CStringAndHash const gc_ConstString_Format = gc_Str<"Format">;
	constexpr CStringAndHash const gc_ConstString_GetDefaultProperties = gc_Str<"GetDefaultProperties">;
	constexpr CStringAndHash const gc_ConstString_GetDrive = gc_Str<"GetDrive">;
	constexpr CStringAndHash const gc_ConstString_GetExtension = gc_Str<"GetExtension">;
	constexpr CStringAndHash const gc_ConstString_GetFile = gc_Str<"GetFile">;
	constexpr CStringAndHash const gc_ConstString_GetFileNoExt = gc_Str<"GetFileNoExt">;
	constexpr CStringAndHash const gc_ConstString_GetLastPaths = gc_Str<"GetLastPaths">;
	constexpr CStringAndHash const gc_ConstString_GetPath = gc_Str<"GetPath">;
	constexpr CStringAndHash const gc_ConstString_GetProperty = gc_Str<"GetProperty">;
	constexpr CStringAndHash const gc_ConstString_Globals = gc_Str<"Globals">;
	constexpr CStringAndHash const gc_ConstString_GreaterThan = gc_Str<"GreaterThan">;
	constexpr CStringAndHash const gc_ConstString_GreaterThanEqual = gc_Str<"GreaterThanEqual">;
	constexpr CStringAndHash const gc_ConstString_HasEntity = gc_Str<"HasEntity">;
	constexpr CStringAndHash const gc_ConstString_HasMember = gc_Str<"HasMember">;
	constexpr CStringAndHash const gc_ConstString_HasParentEntity = gc_Str<"HasParentEntity">;
	constexpr CStringAndHash const gc_ConstString_HasProperty = gc_Str<"HasProperty">;
	constexpr CStringAndHash const gc_ConstString_HashSHA256 = gc_Str<"HashSHA256">;
	constexpr CStringAndHash const gc_ConstString_HashUUID = gc_Str<"HashUUID">;
	constexpr CStringAndHash const gc_ConstString_ImportTargets = gc_Str<"ImportTargets">;
	constexpr CStringAndHash const gc_ConstString_ImportTargets_Defaults = gc_Str<"ImportTargets_Defaults">;
	constexpr CStringAndHash const gc_ConstString_ImportTargets_Properties = gc_Str<"ImportTargets_Properties">;
	constexpr CStringAndHash const gc_ConstString_IsAbsolute = gc_Str<"IsAbsolute">;
	constexpr CStringAndHash const gc_ConstString_IsArray = gc_Str<"IsArray">;
	constexpr CStringAndHash const gc_ConstString_IsBinary = gc_Str<"IsBinary">;
	constexpr CStringAndHash const gc_ConstString_IsBoolean = gc_Str<"IsBoolean">;
	constexpr CStringAndHash const gc_ConstString_IsDate = gc_Str<"IsDate">;
	constexpr CStringAndHash const gc_ConstString_IsDefined = gc_Str<"IsDefined">;
	constexpr CStringAndHash const gc_ConstString_IsEmpty = gc_Str<"IsEmpty">;
	constexpr CStringAndHash const gc_ConstString_IsFloat = gc_Str<"IsFloat">;
	constexpr CStringAndHash const gc_ConstString_IsInteger = gc_Str<"IsInteger">;
	constexpr CStringAndHash const gc_ConstString_IsNull = gc_Str<"IsNull">;
	constexpr CStringAndHash const gc_ConstString_IsObject = gc_Str<"IsObject">;
	constexpr CStringAndHash const gc_ConstString_IsString = gc_Str<"IsString">;
	constexpr CStringAndHash const gc_ConstString_IsStringArray = gc_Str<"IsStringArray">;
	constexpr CStringAndHash const gc_ConstString_IsUserType = gc_Str<"IsUserType">;
	constexpr CStringAndHash const gc_ConstString_IsValid = gc_Str<"IsValid">;
	constexpr CStringAndHash const gc_ConstString_ItemDefinitionGroup = gc_Str<"ItemDefinitionGroup">;
	constexpr CStringAndHash const gc_ConstString_JSONToString = gc_Str<"JSONToString">;
	constexpr CStringAndHash const gc_ConstString_Join = gc_Str<"Join">;
	constexpr CStringAndHash const gc_ConstString_Label = gc_Str<"Label">;
	constexpr CStringAndHash const gc_ConstString_Length = gc_Str<"Length">;
	constexpr CStringAndHash const gc_ConstString_LessThan = gc_Str<"LessThan">;
	constexpr CStringAndHash const gc_ConstString_LessThanEqual = gc_Str<"LessThanEqual">;
	constexpr CStringAndHash const gc_ConstString_Log = gc_Str<"Log">;
	constexpr CStringAndHash const gc_ConstString_LogWithSequence = gc_Str<"LogWithSequence">;
	constexpr CStringAndHash const gc_ConstString_MakeRelative = gc_Str<"MakeRelative">;
	constexpr CStringAndHash const gc_ConstString_MalterlibTime = gc_Str<"MalterlibTime">;
	constexpr CStringAndHash const gc_ConstString_NativePath = gc_Str<"NativePath">;
	constexpr CStringAndHash const gc_ConstString_None = gc_Str<"None">;
	constexpr CStringAndHash const gc_ConstString_Not = gc_Str<"Not">;
	constexpr CStringAndHash const gc_ConstString_NotEqual = gc_Str<"NotEqual">;
	constexpr CStringAndHash const gc_ConstString_Or = gc_Str<"Or">;
	constexpr CStringAndHash const gc_ConstString_OverridingType = gc_Str<"OverridingType">;
	constexpr CStringAndHash const gc_ConstString_Parse = gc_Str<"Parse">;
	constexpr CStringAndHash const gc_ConstString_ParseEJSON = gc_Str<"ParseEJSON">;
	constexpr CStringAndHash const gc_ConstString_ParseFormatString = gc_Str<"ParseFormatString">;
	constexpr CStringAndHash const gc_ConstString_ParseJSON = gc_Str<"ParseJSON">;
	constexpr CStringAndHash const gc_ConstString_PreProject = gc_Str<"PreProject">;
	constexpr CStringAndHash const gc_ConstString_PrecompiledHeaderOutputFile = gc_Str<"PrecompiledHeaderOutputFile">;
	constexpr CStringAndHash const gc_ConstString_Product_Reference = gc_Str<"Product Reference">;
	constexpr CStringAndHash const gc_ConstString_RawMSBuild_ = gc_Str<"RawMSBuild:">;
	constexpr CStringAndHash const gc_ConstString_ReadWindowsRegistry = gc_Str<"ReadWindowsRegistry">;
	constexpr CStringAndHash const gc_ConstString_RelativeBase = gc_Str<"RelativeBase">;
	constexpr CStringAndHash const gc_ConstString_RemoveDuplicates = gc_Str<"RemoveDuplicates">;
	constexpr CStringAndHash const gc_ConstString_RemovePrefix = gc_Str<"RemovePrefix">;
	constexpr CStringAndHash const gc_ConstString_RemoveStartPaths = gc_Str<"RemoveStartPaths">;
	constexpr CStringAndHash const gc_ConstString_RemoveSuffix = gc_Str<"RemoveSuffix">;
	constexpr CStringAndHash const gc_ConstString_RemoveUndefined = gc_Str<"RemoveUndefined">;
	constexpr CStringAndHash const gc_ConstString_ReplaceChars = gc_Str<"ReplaceChars">;
	constexpr CStringAndHash const gc_ConstString_Sanitize = gc_Str<"Sanitize">;
	constexpr CStringAndHash const gc_ConstString_ShortenPath = gc_Str<"ShortenPath">;
	constexpr CStringAndHash const gc_ConstString_Sort = gc_Str<"Sort">;
	constexpr CStringAndHash const gc_ConstString_Split = gc_Str<"Split">;
	constexpr CStringAndHash const gc_ConstString_StartsWith = gc_Str<"StartsWith">;
	constexpr CStringAndHash const gc_ConstString_Switch = gc_Str<"Switch">;
	constexpr CStringAndHash const gc_ConstString_SwitchWithDefault = gc_Str<"SwitchWithDefault">;
	constexpr CStringAndHash const gc_ConstString_SwitchWithError = gc_Str<"SwitchWithError">;
	constexpr CStringAndHash const gc_ConstString_Target_Dependencies = gc_Str<"Target Dependencies">;
	constexpr CStringAndHash const gc_ConstString_ToString = gc_Str<"ToString">;
	constexpr CStringAndHash const gc_ConstString_ToStringCompact = gc_Str<"ToStringCompact">;
	constexpr CStringAndHash const gc_ConstString_Trim = gc_Str<"Trim">;
	constexpr CStringAndHash const gc_ConstString_Unique = gc_Str<"Unique">;
	constexpr CStringAndHash const gc_ConstString_UnixPath = gc_Str<"UnixPath">;
	constexpr CStringAndHash const gc_ConstString_VisualStudio = gc_Str<"VisualStudio">;
	constexpr CStringAndHash const gc_ConstString_Warning = gc_Str<"Warning">;
	constexpr CStringAndHash const gc_ConstString_WindowsPath = gc_Str<"WindowsPath">;
	constexpr CStringAndHash const gc_ConstString_WithPosition = gc_Str<"WithPosition">;
	constexpr CStringAndHash const gc_ConstString_WithPositionOverridingType = gc_Str<"WithPositionOverridingType">;
	constexpr CStringAndHash const gc_ConstString_Xcode = gc_Str<"Xcode">;
	constexpr CStringAndHash const gc_ConstString_com_apple_product_type_library_static = gc_Str<"com.apple.product-type.library.static">;
	constexpr CStringAndHash const gc_ConstString_macOS = gc_Str<"macOS">;
	constexpr CStringAndHash const gc_ConstString_project_pbxproj = gc_Str<"project.pbxproj">;
	constexpr CStringAndHash const gc_ConstString_xcschemes = gc_Str<"xcschemes">;
	constexpr CStringAndHash const gc_ConstString_xcshareddata = gc_Str<"xcshareddata">;
	constexpr CStringAndHash const gc_ConstString__8BC9CEB8_8B4A_11D0_8D11_00A0C91BC942_ = gc_Str<"{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}">;
	constexpr CStringAndHash const gc_ConstString__FAE04EC0_301F_11D3_BF4B_00C04F79EFBC_ = gc_Str<"{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}">;
	constexpr CStringAndHash const gc_ConstString__Automatic = gc_Str<"~Automatic">;

	constexpr CStringAndHash const gc_ConstString_Array = gc_Str<"Array">;
	constexpr CStringAndHash const gc_ConstString_Binary = gc_Str<"Binary">;
	constexpr CStringAndHash const gc_ConstString_Boolean = gc_Str<"Boolean">;
	constexpr CStringAndHash const gc_ConstString_Date = gc_Str<"Date">;
	constexpr CStringAndHash const gc_ConstString_Float = gc_Str<"Float">;
	constexpr CStringAndHash const gc_ConstString_Integer = gc_Str<"Integer">;
	constexpr CStringAndHash const gc_ConstString_Invalid = gc_Str<"Invalid">;
	constexpr CStringAndHash const gc_ConstString_Null = gc_Str<"Null">;
	constexpr CStringAndHash const gc_ConstString_Object = gc_Str<"Object">;
	constexpr CStringAndHash const gc_ConstString_Remove = gc_Str<"Remove">;
	constexpr CStringAndHash const gc_ConstString_UserType = gc_Str<"UserType">;

	constexpr CStringAndHash const gc_ConstString_Registry = gc_Str<"Registry">;
	constexpr CStringAndHash const gc_ConstString__Array = gc_Str<"_Array">;
	constexpr CStringAndHash const gc_ConstString__EntityName = gc_Str<"_EntityName">;
	constexpr CStringAndHash const gc_ConstString__FileName = gc_Str<"_FileName">;
	constexpr CStringAndHash const gc_ConstString__FormatString = gc_Str<"_FormatString">;
	constexpr CStringAndHash const gc_ConstString__Identifier = gc_Str<"_Identifier">;
	constexpr CStringAndHash const gc_ConstString__Left = gc_Str<"_Left">;
	constexpr CStringAndHash const gc_ConstString__OutputFormat = gc_Str<"_OutputFormat">;
	constexpr CStringAndHash const gc_ConstString__ParseFormat = gc_Str<"_ParseFormat">;
	constexpr CStringAndHash const gc_ConstString__Path = gc_Str<"_Path">;
	constexpr CStringAndHash const gc_ConstString__Properties = gc_Str<"_Properties">;
	constexpr CStringAndHash const gc_ConstString__Right = gc_Str<"_Right">;
	constexpr CStringAndHash const gc_ConstString__Source = gc_Str<"_Source">;
	constexpr CStringAndHash const gc_ConstString__String = gc_Str<"_String">;
	constexpr CStringAndHash const gc_ConstString__StringToHash = gc_Str<"_StringToHash">;
	constexpr CStringAndHash const gc_ConstString__StringToParse = gc_Str<"_StringToParse">;
	constexpr CStringAndHash const gc_ConstString__ToReturn = gc_Str<"_ToReturn">;
	constexpr CStringAndHash const gc_ConstString__Value = gc_Str<"_Value">;
	constexpr CStringAndHash const gc_ConstString__VariableToGetTypeFrom = gc_Str<"_VariableToGetTypeFrom">;
	constexpr CStringAndHash const gc_ConstString__Wildcard = gc_Str<"_Wildcard">;
	constexpr CStringAndHash const gc_ConstString_p_Source = gc_Str<"p_Source">;
	constexpr CStringAndHash const gc_ConstString_p_SwitchValues = gc_Str<"p_SwitchValues">;
	constexpr CStringAndHash const gc_ConstString_p_Values = gc_Str<"p_Values">;
	constexpr CStringAndHash const gc_ConstString_rfc1034 = gc_Str<"rfc1034">;

	constexpr CStringAndHash const gc_ConstString__24 = gc_Str<"%24">;
	constexpr CStringAndHash const gc_ConstString__25 = gc_Str<"%25">;
	constexpr CStringAndHash const gc_ConstString__27 = gc_Str<"%27">;
	constexpr CStringAndHash const gc_ConstString__28 = gc_Str<"%28">;
	constexpr CStringAndHash const gc_ConstString__29 = gc_Str<"%29">;
	constexpr CStringAndHash const gc_ConstString__2A = gc_Str<"%2A">;
	constexpr CStringAndHash const gc_ConstString__3B = gc_Str<"%3B">;
	constexpr CStringAndHash const gc_ConstString__3F = gc_Str<"%3F">;
	constexpr CStringAndHash const gc_ConstString__40 = gc_Str<"%40">;
	constexpr CStringAndHash const gc_ConstString____DS_Store = gc_Str<"*/.DS_Store">;
	constexpr CStringAndHash const gc_ConstString_AlphaNum = gc_Str<"AlphaNum">;
	constexpr CStringAndHash const gc_ConstString_Bare = gc_Str<"Bare">;
	constexpr CStringAndHash const gc_ConstString_Classes = gc_Str<"Classes">;
	constexpr CStringAndHash const gc_ConstString_Contributing_to_value = gc_Str<"Contributing to value">;
	constexpr CStringAndHash const gc_ConstString_CurrentUser = gc_Str<"CurrentUser">;
	constexpr CStringAndHash const gc_ConstString_LocalMachine = gc_Str<"LocalMachine">;
	constexpr CStringAndHash const gc_ConstString_Parent = gc_Str<"Parent">;
	constexpr CStringAndHash const gc_ConstString_Reconcile = gc_Str<"Reconcile">;
	constexpr CStringAndHash const gc_ConstString_ReconcileForce = gc_Str<"ReconcileForce">;
	constexpr CStringAndHash const gc_ConstString_ReconcileNoOptions = gc_Str<"ReconcileNoOptions">;
	constexpr CStringAndHash const gc_ConstString_ReconcileRemoved = gc_Str<"ReconcileRemoved">;
	constexpr CStringAndHash const gc_ConstString_RepoBranch = gc_Str<"RepoBranch">;
	constexpr CStringAndHash const gc_ConstString_RepoName = gc_Str<"RepoName">;
	constexpr CStringAndHash const gc_ConstString_RepoOnlyChanged = gc_Str<"RepoOnlyChanged">;
	constexpr CStringAndHash const gc_ConstString_RepoTags = gc_Str<"RepoTags">;
	constexpr CStringAndHash const gc_ConstString_RepoType = gc_Str<"RepoType">;
	constexpr CStringAndHash const gc_ConstString_Return = gc_Str<"Return">;
	constexpr CStringAndHash const gc_ConstString_TraceCondition = gc_Str<"TraceCondition">;
	constexpr CStringAndHash const gc_ConstString_TraceEval = gc_Str<"TraceEval">;
	constexpr CStringAndHash const gc_ConstString_TraceEvalSuccess = gc_Str<"TraceEvalSuccess">;
	constexpr CStringAndHash const gc_ConstString_Win64_Classes = gc_Str<"Win64_Classes">;
	constexpr CStringAndHash const gc_ConstString_Win64_CurrentUser = gc_Str<"Win64_CurrentUser">;
	constexpr CStringAndHash const gc_ConstString_Win64_LocalMachine = gc_Str<"Win64_LocalMachine">;
	constexpr CStringAndHash const gc_ConstString__ArrayToExplode = gc_Str<"_ArrayToExplode">;
	constexpr CStringAndHash const gc_ConstString__ArrayToSearch = gc_Str<"_ArrayToSearch">;
	constexpr CStringAndHash const gc_ConstString__IndentString = gc_Str<"_IndentString">;
	constexpr CStringAndHash const gc_ConstString__JoinBy = gc_Str<"_JoinBy">;
	constexpr CStringAndHash const gc_ConstString__ElementToFind = gc_Str<"_ElementToFind">;
	constexpr CStringAndHash const gc_ConstString__Base = gc_Str<"_Base">;
	constexpr CStringAndHash const gc_ConstString__Boolean = gc_Str<"_Boolean">;
	constexpr CStringAndHash const gc_ConstString__Default = gc_Str<"_Default">;
	constexpr CStringAndHash const gc_ConstString__EJSON = gc_Str<"_EJSON">;
	constexpr CStringAndHash const gc_ConstString__EntityType = gc_Str<"_EntityType">;
	constexpr CStringAndHash const gc_ConstString__Error = gc_Str<"_Error">;
	constexpr CStringAndHash const gc_ConstString__ExcludeWildcards = gc_Str<"_ExcludeWildcards">;
	constexpr CStringAndHash const gc_ConstString__Executable = gc_Str<"_Executable">;
	constexpr CStringAndHash const gc_ConstString__ExplodeFunction = gc_Str<"_ExplodeFunction">;
	constexpr CStringAndHash const gc_ConstString__Format = gc_Str<"_Format">;
	constexpr CStringAndHash const gc_ConstString__Inputs = gc_Str<"_Inputs">;
	constexpr CStringAndHash const gc_ConstString__JSON = gc_Str<"_JSON">;
	constexpr CStringAndHash const gc_ConstString__Key = gc_Str<"_Key">;
	constexpr CStringAndHash const gc_ConstString__Length = gc_Str<"_Length">;
	constexpr CStringAndHash const gc_ConstString__Member = gc_Str<"_Member">;
	constexpr CStringAndHash const gc_ConstString__NumPaths = gc_Str<"_NumPaths">;
	constexpr CStringAndHash const gc_ConstString__Positions = gc_Str<"_Positions">;
	constexpr CStringAndHash const gc_ConstString__Property = gc_Str<"_Property">;
	constexpr CStringAndHash const gc_ConstString__PropertyType = gc_Str<"_PropertyType">;
	constexpr CStringAndHash const gc_ConstString__ReplaceWith = gc_Str<"_ReplaceWith">;
	constexpr CStringAndHash const gc_ConstString__ReplaceWithString = gc_Str<"_ReplaceWithString">;
	constexpr CStringAndHash const gc_ConstString__Root = gc_Str<"_Root">;
	constexpr CStringAndHash const gc_ConstString__SearchFor = gc_Str<"_SearchFor">;
	constexpr CStringAndHash const gc_ConstString__SearchForCharacters = gc_Str<"_SearchForCharacters">;
	constexpr CStringAndHash const gc_ConstString__SplitBy = gc_Str<"_SplitBy">;
	constexpr CStringAndHash const gc_ConstString__StateFile = gc_Str<"_StateFile">;
	constexpr CStringAndHash const gc_ConstString__StringToFind = gc_Str<"_StringToFind">;
	constexpr CStringAndHash const gc_ConstString__StringToRemove = gc_Str<"_StringToRemove">;
	constexpr CStringAndHash const gc_ConstString__Strings = gc_Str<"_Strings">;
	constexpr CStringAndHash const gc_ConstString__Time = gc_Str<"_Time">;
	constexpr CStringAndHash const gc_ConstString__Type = gc_Str<"_Type">;
	constexpr CStringAndHash const gc_ConstString__ValueName = gc_Str<"_ValueName">;
	constexpr CStringAndHash const gc_ConstString__WildcardToSearchFor = gc_Str<"_WildcardToSearchFor">;
	constexpr CStringAndHash const gc_ConstString__bFile = gc_Str<"_bFile">;
	constexpr CStringAndHash const gc_ConstString_auto = gc_Str<"auto">;
	constexpr CStringAndHash const gc_ConstString_bash = gc_Str<"bash">;
	constexpr CStringAndHash const gc_ConstString_delete = gc_Str<"delete">;
	constexpr CStringAndHash const gc_ConstString_leave = gc_Str<"leave">;
	constexpr CStringAndHash const gc_ConstString_p_ErrorValues = gc_Str<"p_ErrorValues">;
	constexpr CStringAndHash const gc_ConstString_p_LogValues = gc_Str<"p_LogValues">;
	constexpr CStringAndHash const gc_ConstString_p_Params = gc_Str<"p_Params">;
	constexpr CStringAndHash const gc_ConstString_p_Paths = gc_Str<"p_Paths">;
	constexpr CStringAndHash const gc_ConstString_p_ToConcat = gc_Str<"p_ToConcat">;
	constexpr CStringAndHash const gc_ConstString_p_Types = gc_Str<"p_Types">;
	constexpr CStringAndHash const gc_ConstString_rebase = gc_Str<"rebase">;
	constexpr CStringAndHash const gc_ConstString_reset = gc_Str<"reset">;
	constexpr CStringAndHash const gc_ConstString_OptionalChaining = gc_Str<"OptionalChaining">;
	constexpr CStringAndHash const gc_ConstString_Accessor = gc_Str<"Accessor">;

	constexpr CStringAndHash const gc_ConstString_Symbol_Inherit = gc_Str<"{578185E0-2E2A-4481-A34E-BCC3F64CDCA2}">;

	void fg_CacheConstantStrings(CStringCache &o_StringCache)
	{
		o_StringCache.f_AddString(gc_ConstString_Empty, gc_ConstString_Empty.f_Hash());

		DMibLock(o_StringCache.m_Lock);
		o_StringCache.f_AddConstantString(gc_ConstString_Accessors);
		o_StringCache.f_AddConstantString(gc_ConstString_any);
		o_StringCache.f_AddConstantString(gc_ConstString_AppendExpression);
		o_StringCache.f_AddConstantString(gc_ConstString_Architecture);
		o_StringCache.f_AddConstantString(gc_ConstString_Argument);
		o_StringCache.f_AddConstantString(gc_ConstString_binary);
		o_StringCache.f_AddConstantString(gc_ConstString_BinaryOperator);
		o_StringCache.f_AddConstantString(gc_ConstString_bool);
		o_StringCache.f_AddConstantString(gc_ConstString_BuildSystemToken);
		o_StringCache.f_AddConstantString(gc_ConstString_Column);
		o_StringCache.f_AddConstantString(gc_ConstString_Conditional);
		o_StringCache.f_AddConstantString(gc_ConstString_Configuration);
		o_StringCache.f_AddConstantString(gc_ConstString_date);
		o_StringCache.f_AddConstantString(gc_ConstString_DefaultBranch);
		o_StringCache.f_AddConstantString(gc_ConstString_DefaultType);
		o_StringCache.f_AddConstantString(gc_ConstString_DefaultValue);
		o_StringCache.f_AddConstantString(gc_ConstString_Define);
		o_StringCache.f_AddConstantString(gc_ConstString_Disabled);
		o_StringCache.f_AddConstantString(gc_ConstString_Ellipsis);
		o_StringCache.f_AddConstantString(gc_ConstString_EntityType);
		o_StringCache.f_AddConstantString(gc_ConstString_ERROR);
		o_StringCache.f_AddConstantString(gc_ConstString_EvalString);
		o_StringCache.f_AddConstantString(gc_ConstString_Expression);
		o_StringCache.f_AddConstantString(gc_ConstString_File);
		o_StringCache.f_AddConstantString(gc_ConstString_float);
		o_StringCache.f_AddConstantString(gc_ConstString_FullEval);
		o_StringCache.f_AddConstantString(gc_ConstString_Function);
		o_StringCache.f_AddConstantString(gc_ConstString_FunctionType);
		o_StringCache.f_AddConstantString(gc_ConstString_Group);
		o_StringCache.f_AddConstantString(gc_ConstStringDynamic_DPlatform);
		o_StringCache.f_AddConstantString(gc_ConstStringDynamic_DPlatformFamily);
		o_StringCache.f_AddConstantString(gc_ConstStringDynamic_DArchitecture);
		o_StringCache.f_AddConstantString(gc_ConstString_identifier);
		o_StringCache.f_AddConstantString(gc_ConstString_Identifier);
		o_StringCache.f_AddConstantString(gc_ConstString_IdentifierReference);
		o_StringCache.f_AddConstantString(gc_ConstString_Identity);
		o_StringCache.f_AddConstantString(gc_ConstString_IdentityAsAbsolutePath);
		o_StringCache.f_AddConstantString(gc_ConstString_IdentityPath);
		o_StringCache.f_AddConstantString(gc_ConstString_EntityPath);
		o_StringCache.f_AddConstantString(gc_ConstString_InnerType);
		o_StringCache.f_AddConstantString(gc_ConstString_int);
		o_StringCache.f_AddConstantString(gc_ConstString_JSONAccessor);
		o_StringCache.f_AddConstantString(gc_ConstString_KeyLogicalOperator);
		o_StringCache.f_AddConstantString(gc_ConstString_KeyPrefixOperator);
		o_StringCache.f_AddConstantString(gc_ConstString_Namespace);
		o_StringCache.f_AddConstantString(gc_ConstString_Left);
		o_StringCache.f_AddConstantString(gc_ConstString_Legacy);
		o_StringCache.f_AddConstantString(gc_ConstString_Line);
		o_StringCache.f_AddConstantString(gc_ConstString_Message);
		o_StringCache.f_AddConstantString(gc_ConstString_Name);
		o_StringCache.f_AddConstantString(gc_ConstString_OneOf);
		o_StringCache.f_AddConstantString(gc_ConstString_OneOfList);
		o_StringCache.f_AddConstantString(gc_ConstString_Operator);
		o_StringCache.f_AddConstantString(gc_ConstString_Optional);
		o_StringCache.f_AddConstantString(gc_ConstString_Param);
		o_StringCache.f_AddConstantString(gc_ConstString_Parameters);
		o_StringCache.f_AddConstantString(gc_ConstString_Params);
		o_StringCache.f_AddConstantString(gc_ConstString_Paren);
		o_StringCache.f_AddConstantString(gc_ConstString_Platform);
		o_StringCache.f_AddConstantString(gc_ConstString_PostFunction);
		o_StringCache.f_AddConstantString(gc_ConstString_PrefixOperator);
		o_StringCache.f_AddConstantString(gc_ConstString_PropertyType);
		o_StringCache.f_AddConstantString(gc_ConstString_ReturnType);
		o_StringCache.f_AddConstantString(gc_ConstString_Right);
		o_StringCache.f_AddConstantString(gc_ConstString_RootValue);
		o_StringCache.f_AddConstantString(gc_ConstString_String);
		o_StringCache.f_AddConstantString(gc_ConstString_string);
		o_StringCache.f_AddConstantString(gc_ConstString_Subscript);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_AccessObject);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_AppendObject);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_BitwiseNot);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_ConfigurationPrefix);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_Ellipsis);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_EntityPrefix);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_LogicalAnd);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_LogicalNot);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_LogicalNotNot);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_LogicalOr);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_MakeReference);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_OperatorAdd);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_OperatorAnd);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_OperatorAppend);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_OperatorBitwiseAnd);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_OperatorBitwiseLeftShift);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_OperatorBitwiseOr);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_OperatorBitwiseRightShift);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_OperatorBitwiseXor);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_OperatorDivide);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_OperatorEqual);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_OperatorGreaterThan);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_OperatorGreaterThanEqual);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_OperatorLessThan);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_OperatorLessThanEqual);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_OperatorMatchEqual);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_OperatorMatchNotEqual);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_OperatorModulus);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_OperatorMultiply);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_OperatorNotEqual);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_OperatorOr);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_OperatorNullishCoalescing);		
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_OperatorPrepend);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_OperatorSubtract);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_Optional);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_PragmaPrefix);
		o_StringCache.f_AddConstantString(gc_ConstString_namespace);
		o_StringCache.f_AddConstantString(gc_ConstString_Target);
		o_StringCache.f_AddConstantString(gc_ConstString_Ternary);
		o_StringCache.f_AddConstantString(gc_ConstString_Type);
		o_StringCache.f_AddConstantString(gc_ConstString_TypeDefaulted);
		o_StringCache.f_AddConstantString(gc_ConstString_TypeName);
		o_StringCache.f_AddConstantString(gc_ConstString_URL);
		o_StringCache.f_AddConstantString(gc_ConstString_Value);
		o_StringCache.f_AddConstantString(gc_ConstString_void);
		o_StringCache.f_AddConstantString(gc_ConstString_WildcardString);
		o_StringCache.f_AddConstantString(gc_ConstString_Write);
		o_StringCache.f_AddConstantString(gc_ConstString_VisualStudioRoot);
		o_StringCache.f_AddConstantString(gc_ConstString_XInternalPrecompiledHeaderOutputFile);
		o_StringCache.f_AddConstantString(gc_ConstString_Replace);
		o_StringCache.f_AddConstantString(gc_ConstString_Find);
		o_StringCache.f_AddConstantString(gc_ConstString_MakeAbsolute);
		o_StringCache.f_AddConstantString(gc_ConstString_Error);
		o_StringCache.f_AddConstantString(gc_ConstString_Root);
		o_StringCache.f_AddConstantString(gc_ConstString_Workspace);
		o_StringCache.f_AddConstantString(gc_ConstString_Dependency);
		o_StringCache.f_AddConstantString(gc_ConstString_GeneratorSetting);
		o_StringCache.f_AddConstantString(gc_ConstString_GenerateFile);
		o_StringCache.f_AddConstantString(gc_ConstString_Import);
		o_StringCache.f_AddConstantString(gc_ConstString_Repository);
		o_StringCache.f_AddConstantString(gc_ConstString_CreateTemplate);
		o_StringCache.f_AddConstantString(gc_ConstString_Property);
		o_StringCache.f_AddConstantString(gc_ConstString_Compile);
		o_StringCache.f_AddConstantString(gc_ConstString_this);
		o_StringCache.f_AddConstantString(gc_ConstString_Builtin);
		o_StringCache.f_AddConstantString(gc_ConstString_undefined);
		o_StringCache.f_AddConstantString(gc_ConstString_3FFADB4E_9D9D_4CD7_8FA8_539C6ABF79BA);
		o_StringCache.f_AddConstantString(gc_ConstString_PBXFileReference);
		o_StringCache.f_AddConstantString(gc_ConstString_Positions);
		o_StringCache.f_AddConstantString(gc_ConstString_lastKnownFileType);
		o_StringCache.f_AddConstantString(gc_ConstString_explicitFileType);
		o_StringCache.f_AddConstantString(gc_ConstString_fileEncoding);
		o_StringCache.f_AddConstantString(gc_ConstString_tabWidth);
		o_StringCache.f_AddConstantString(gc_ConstString_usesTabs);
		o_StringCache.f_AddConstantString(gc_ConstString_indentWidth);
		o_StringCache.f_AddConstantString(gc_ConstString_XCConfigs);
		o_StringCache.f_AddConstantString(gc_ConstString_VSSettings);		
		o_StringCache.f_AddConstantString(gc_ConstString_YES);
		o_StringCache.f_AddConstantString(gc_ConstString_NO);
		o_StringCache.f_AddConstantString(gc_ConstString_Flags);
		o_StringCache.f_AddConstantString(gc_ConstString_ProductType);
		o_StringCache.f_AddConstantString(gc_ConstString_Entity);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_Cpp);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_CppManaged);
		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_ObjCpp);
		o_StringCache.f_AddConstantString(gc_ConstString_PostBuildScript);
		o_StringCache.f_AddConstantString(gc_ConstString_ToolBuildScript);
		o_StringCache.f_AddConstantString(gc_ConstString_ToolBuildScriptInputs);
		o_StringCache.f_AddConstantString(gc_ConstString_ToolBuildScriptOutputs);
		o_StringCache.f_AddConstantString(gc_ConstString_PreBuildScript);
		o_StringCache.f_AddConstantString(gc_ConstString_GCC_PRECOMPILE_PREFIX_HEADER);
		o_StringCache.f_AddConstantString(gc_ConstString_GCC_PREFIX_HEADER);
		o_StringCache.f_AddConstantString(gc_ConstString_C);
		o_StringCache.f_AddConstantString(gc_ConstString_ObjC);
		o_StringCache.f_AddConstantString(gc_ConstString_Assembler);
		o_StringCache.f_AddConstantString(gc_ConstString_MOC_OUTPUT_PATTERN);
		o_StringCache.f_AddConstantString(gc_ConstString_FilesExcludedFromCompile);
		o_StringCache.f_AddConstantString(gc_ConstString_true);
		o_StringCache.f_AddConstantString(gc_ConstString_false);
		o_StringCache.f_AddConstantString(gc_ConstString_null);
		o_StringCache.f_AddConstantString(gc_ConstString_define);
		o_StringCache.f_AddConstantString(gc_ConstString_function);
		o_StringCache.f_AddConstantString(gc_ConstString_type);
		o_StringCache.f_AddConstantString(gc_ConstString_one_of);
		o_StringCache.f_AddConstantString(gc_ConstString_nolink);
		o_StringCache.f_AddConstantString(gc_ConstString_PRODUCT_NAME);
		o_StringCache.f_AddConstantString(gc_ConstString_EXECUTABLE_EXTENSION);
		o_StringCache.f_AddConstantString(gc_ConstString_BUILT_PRODUCTS_DIR);
		o_StringCache.f_AddConstantString(gc_ConstString_CONFIGURATION_BUILD_DIR);
		o_StringCache.f_AddConstantString(gc_ConstString_NATIVE_ARCH_ACTUAL);
		o_StringCache.f_AddConstantString(gc_ConstString_BUILD_DIR);
		o_StringCache.f_AddConstantString(gc_ConstString_BUILD_ROOT);
		o_StringCache.f_AddConstantString(gc_ConstString_CONFIGURATION_TEMP_DIR);
		o_StringCache.f_AddConstantString(gc_ConstString_OBJROOT);
		o_StringCache.f_AddConstantString(gc_ConstString_PROJECT_DERIVED_FILE_DIR);
		o_StringCache.f_AddConstantString(gc_ConstString_PROJECT_TEMP_DIR);
		o_StringCache.f_AddConstantString(gc_ConstString_PROJECT_TEMP_ROOT);
		o_StringCache.f_AddConstantString(gc_ConstString_SHARED_PRECOMPS_DIR);
		o_StringCache.f_AddConstantString(gc_ConstString_SYMROOT);
		o_StringCache.f_AddConstantString(gc_ConstString_TARGET_TEMP_DIR);
		o_StringCache.f_AddConstantString(gc_ConstString_TEMP_FILES_DIR);
		o_StringCache.f_AddConstantString(gc_ConstString_TEMP_FILE_DIR);
		o_StringCache.f_AddConstantString(gc_ConstString_TEMP_ROOT);
		o_StringCache.f_AddConstantString(gc_ConstString_MODULE_CACHE_DIR);
		o_StringCache.f_AddConstantString(gc_ConstString_generatedContainer);
		o_StringCache.f_AddConstantString(gc_ConstString_StaticLibrary);
		o_StringCache.f_AddConstantString(gc_ConstString_SharedDynamicLibrary);
		o_StringCache.f_AddConstantString(gc_ConstString_Custom);
		o_StringCache.f_AddConstantString(gc_ConstString_argument);
		o_StringCache.f_AddConstantString(gc_ConstString_LocalDebuggerCommand);
		o_StringCache.f_AddConstantString(gc_ConstString_customWorkingDirectory);
		o_StringCache.f_AddConstantString(gc_ConstString_CommandLineArgument);
		o_StringCache.f_AddConstantString(gc_ConstString_LIBRARY_SEARCH_PATHS);
		o_StringCache.f_AddConstantString(gc_ConstString_OTHER_LDFLAGS);
		o_StringCache.f_AddConstantString(gc_ConstString_LDFlagsFirst);
		o_StringCache.f_AddConstantString(gc_ConstString_OTHER_LIBTOOLFLAGS);
		o_StringCache.f_AddConstantString(gc_ConstString_PropertyGroup);
		o_StringCache.f_AddConstantString(gc_ConstString_XInternalCreate);
		o_StringCache.f_AddConstantString(gc_ConstString_CMakeLanguage);
		o_StringCache.f_AddConstantString(gc_ConstString_MalterlibLanguage);
		o_StringCache.f_AddConstantString(gc_ConstString_Match);
		o_StringCache.f_AddConstantString(gc_ConstString_FilePatterns);
		o_StringCache.f_AddConstantString(gc_ConstString_ExcludeFilePatterns);
		o_StringCache.f_AddConstantString(gc_ConstString_ApplyToPaths);
		o_StringCache.f_AddConstantString(gc_ConstString_Include);
		o_StringCache.f_AddConstantString(gc_ConstString_XcodeGeneratorDependencyFiles);
		o_StringCache.f_AddConstantString(gc_ConstString_LfsReleaseStore);

		o_StringCache.f_AddConstantString(gc_ConstString_Settings);
		o_StringCache.f_AddConstantString(gc_ConstString_17_0);
		o_StringCache.f_AddConstantString(gc_ConstString_And);
		o_StringCache.f_AddConstantString(gc_ConstString_AppendPath);
		o_StringCache.f_AddConstantString(gc_ConstString_AsBoolean);
		o_StringCache.f_AddConstantString(gc_ConstString_AsFloat);
		o_StringCache.f_AddConstantString(gc_ConstString_AsInteger);
		o_StringCache.f_AddConstantString(gc_ConstString_AsString);
		o_StringCache.f_AddConstantString(gc_ConstString_CMakeIntermediateDirectory);
		o_StringCache.f_AddConstantString(gc_ConstString_Concat);
		o_StringCache.f_AddConstantString(gc_ConstString_Condition);
		o_StringCache.f_AddConstantString(gc_ConstString_Configurations);
		o_StringCache.f_AddConstantString(gc_ConstString_ContainsListElement);
		o_StringCache.f_AddConstantString(gc_ConstString_Context);
		o_StringCache.f_AddConstantString(gc_ConstString_DateTime);
		o_StringCache.f_AddConstantString(gc_ConstString_EJSONToString);
		o_StringCache.f_AddConstantString(gc_ConstString_EndsWith);
		o_StringCache.f_AddConstantString(gc_ConstString_Equal);
		o_StringCache.f_AddConstantString(gc_ConstString_ErrorWithPositions);
		o_StringCache.f_AddConstantString(gc_ConstString_Escape);
		o_StringCache.f_AddConstantString(gc_ConstString_EscapeBash);
		o_StringCache.f_AddConstantString(gc_ConstString_EscapeHost);
		o_StringCache.f_AddConstantString(gc_ConstString_EscapeMSBuild);
		o_StringCache.f_AddConstantString(gc_ConstString_EscapeWindows);
		o_StringCache.f_AddConstantString(gc_ConstString_ExcludedFromBuild);
		o_StringCache.f_AddConstantString(gc_ConstString_ExecuteCommand);
		o_StringCache.f_AddConstantString(gc_ConstString_File_entity);
		o_StringCache.f_AddConstantString(gc_ConstString_FindGetLine);
		o_StringCache.f_AddConstantString(gc_ConstString_FindNoCase);
		o_StringCache.f_AddConstantString(gc_ConstString_ForEach);
		o_StringCache.f_AddConstantString(gc_ConstString_Format);
		o_StringCache.f_AddConstantString(gc_ConstString_GetDefaultProperties);
		o_StringCache.f_AddConstantString(gc_ConstString_GetDrive);
		o_StringCache.f_AddConstantString(gc_ConstString_GetExtension);
		o_StringCache.f_AddConstantString(gc_ConstString_GetFile);
		o_StringCache.f_AddConstantString(gc_ConstString_GetFileNoExt);
		o_StringCache.f_AddConstantString(gc_ConstString_GetLastPaths);
		o_StringCache.f_AddConstantString(gc_ConstString_GetPath);
		o_StringCache.f_AddConstantString(gc_ConstString_GetProperty);
		o_StringCache.f_AddConstantString(gc_ConstString_Globals);
		o_StringCache.f_AddConstantString(gc_ConstString_GreaterThan);
		o_StringCache.f_AddConstantString(gc_ConstString_GreaterThanEqual);
		o_StringCache.f_AddConstantString(gc_ConstString_HasEntity);
		o_StringCache.f_AddConstantString(gc_ConstString_HasMember);
		o_StringCache.f_AddConstantString(gc_ConstString_HasParentEntity);
		o_StringCache.f_AddConstantString(gc_ConstString_HasProperty);
		o_StringCache.f_AddConstantString(gc_ConstString_HashSHA256);
		o_StringCache.f_AddConstantString(gc_ConstString_HashUUID);
		o_StringCache.f_AddConstantString(gc_ConstString_ImportTargets);
		o_StringCache.f_AddConstantString(gc_ConstString_ImportTargets_Defaults);
		o_StringCache.f_AddConstantString(gc_ConstString_ImportTargets_Properties);
		o_StringCache.f_AddConstantString(gc_ConstString_IsAbsolute);
		o_StringCache.f_AddConstantString(gc_ConstString_IsArray);
		o_StringCache.f_AddConstantString(gc_ConstString_IsBinary);
		o_StringCache.f_AddConstantString(gc_ConstString_IsBoolean);
		o_StringCache.f_AddConstantString(gc_ConstString_IsDate);
		o_StringCache.f_AddConstantString(gc_ConstString_IsDefined);
		o_StringCache.f_AddConstantString(gc_ConstString_IsEmpty);
		o_StringCache.f_AddConstantString(gc_ConstString_IsFloat);
		o_StringCache.f_AddConstantString(gc_ConstString_IsInteger);
		o_StringCache.f_AddConstantString(gc_ConstString_IsNull);
		o_StringCache.f_AddConstantString(gc_ConstString_IsObject);
		o_StringCache.f_AddConstantString(gc_ConstString_IsString);
		o_StringCache.f_AddConstantString(gc_ConstString_IsStringArray);
		o_StringCache.f_AddConstantString(gc_ConstString_IsUserType);
		o_StringCache.f_AddConstantString(gc_ConstString_IsValid);
		o_StringCache.f_AddConstantString(gc_ConstString_ItemDefinitionGroup);
		o_StringCache.f_AddConstantString(gc_ConstString_JSONToString);
		o_StringCache.f_AddConstantString(gc_ConstString_Join);
		o_StringCache.f_AddConstantString(gc_ConstString_Label);
		o_StringCache.f_AddConstantString(gc_ConstString_Length);
		o_StringCache.f_AddConstantString(gc_ConstString_LessThan);
		o_StringCache.f_AddConstantString(gc_ConstString_LessThanEqual);
		o_StringCache.f_AddConstantString(gc_ConstString_Log);
		o_StringCache.f_AddConstantString(gc_ConstString_LogWithSequence);
		o_StringCache.f_AddConstantString(gc_ConstString_MakeRelative);
		o_StringCache.f_AddConstantString(gc_ConstString_MalterlibTime);
		o_StringCache.f_AddConstantString(gc_ConstString_NativePath);
		o_StringCache.f_AddConstantString(gc_ConstString_None);
		o_StringCache.f_AddConstantString(gc_ConstString_Not);
		o_StringCache.f_AddConstantString(gc_ConstString_NotEqual);
		o_StringCache.f_AddConstantString(gc_ConstString_Or);
		o_StringCache.f_AddConstantString(gc_ConstString_OverridingType);
		o_StringCache.f_AddConstantString(gc_ConstString_Parse);
		o_StringCache.f_AddConstantString(gc_ConstString_ParseEJSON);
		o_StringCache.f_AddConstantString(gc_ConstString_ParseFormatString);
		o_StringCache.f_AddConstantString(gc_ConstString_ParseJSON);
		o_StringCache.f_AddConstantString(gc_ConstString_PreProject);
		o_StringCache.f_AddConstantString(gc_ConstString_PrecompiledHeaderOutputFile);
		o_StringCache.f_AddConstantString(gc_ConstString_Product_Reference);
		o_StringCache.f_AddConstantString(gc_ConstString_RawMSBuild_);
		o_StringCache.f_AddConstantString(gc_ConstString_ReadWindowsRegistry);
		o_StringCache.f_AddConstantString(gc_ConstString_RelativeBase);
		o_StringCache.f_AddConstantString(gc_ConstString_RemoveDuplicates);
		o_StringCache.f_AddConstantString(gc_ConstString_RemovePrefix);
		o_StringCache.f_AddConstantString(gc_ConstString_RemoveStartPaths);
		o_StringCache.f_AddConstantString(gc_ConstString_RemoveSuffix);
		o_StringCache.f_AddConstantString(gc_ConstString_RemoveUndefined);
		o_StringCache.f_AddConstantString(gc_ConstString_ReplaceChars);
		o_StringCache.f_AddConstantString(gc_ConstString_Sanitize);
		o_StringCache.f_AddConstantString(gc_ConstString_ShortenPath);
		o_StringCache.f_AddConstantString(gc_ConstString_Sort);
		o_StringCache.f_AddConstantString(gc_ConstString_Split);
		o_StringCache.f_AddConstantString(gc_ConstString_StartsWith);
		o_StringCache.f_AddConstantString(gc_ConstString_Switch);
		o_StringCache.f_AddConstantString(gc_ConstString_SwitchWithDefault);
		o_StringCache.f_AddConstantString(gc_ConstString_SwitchWithError);
		o_StringCache.f_AddConstantString(gc_ConstString_Target_Dependencies);
		o_StringCache.f_AddConstantString(gc_ConstString_ToString);
		o_StringCache.f_AddConstantString(gc_ConstString_ToStringCompact);
		o_StringCache.f_AddConstantString(gc_ConstString_Trim);
		o_StringCache.f_AddConstantString(gc_ConstString_Unique);
		o_StringCache.f_AddConstantString(gc_ConstString_UnixPath);
		o_StringCache.f_AddConstantString(gc_ConstString_VisualStudio);
		o_StringCache.f_AddConstantString(gc_ConstString_Warning);
		o_StringCache.f_AddConstantString(gc_ConstString_WindowsPath);
		o_StringCache.f_AddConstantString(gc_ConstString_WithPosition);
		o_StringCache.f_AddConstantString(gc_ConstString_WithPositionOverridingType);
		o_StringCache.f_AddConstantString(gc_ConstString_Xcode);
		o_StringCache.f_AddConstantString(gc_ConstString_com_apple_product_type_library_static);
		o_StringCache.f_AddConstantString(gc_ConstString_macOS);
		o_StringCache.f_AddConstantString(gc_ConstString_project_pbxproj);
		o_StringCache.f_AddConstantString(gc_ConstString_xcschemes);
		o_StringCache.f_AddConstantString(gc_ConstString_xcshareddata);
		o_StringCache.f_AddConstantString(gc_ConstString__8BC9CEB8_8B4A_11D0_8D11_00A0C91BC942_);
		o_StringCache.f_AddConstantString(gc_ConstString__FAE04EC0_301F_11D3_BF4B_00C04F79EFBC_);
		o_StringCache.f_AddConstantString(gc_ConstString__Automatic);

		o_StringCache.f_AddConstantStringWithoutHash(CEJSONConstStrings::mc_Date);
		o_StringCache.f_AddConstantStringWithoutHash(CEJSONConstStrings::mc_Binary);
		o_StringCache.f_AddConstantStringWithoutHash(CEJSONConstStrings::mc_Type);
		o_StringCache.f_AddConstantStringWithoutHash(CEJSONConstStrings::mc_Value);
		o_StringCache.f_AddConstantStringWithoutHash(CEJSONConstStrings::mc_Escape);

		o_StringCache.f_AddConstantString(gc_ConstString_Array);
		o_StringCache.f_AddConstantString(gc_ConstString_Binary);
		o_StringCache.f_AddConstantString(gc_ConstString_Boolean);
		o_StringCache.f_AddConstantString(gc_ConstString_Date);
		o_StringCache.f_AddConstantString(gc_ConstString_Float);
		o_StringCache.f_AddConstantString(gc_ConstString_Integer);
		o_StringCache.f_AddConstantString(gc_ConstString_Invalid);
		o_StringCache.f_AddConstantString(gc_ConstString_Null);
		o_StringCache.f_AddConstantString(gc_ConstString_Object);
		o_StringCache.f_AddConstantString(gc_ConstString_Remove);
		o_StringCache.f_AddConstantString(gc_ConstString_UserType);

		o_StringCache.f_AddConstantString(gc_ConstString_Registry);
		o_StringCache.f_AddConstantString(gc_ConstString__Array);
		o_StringCache.f_AddConstantString(gc_ConstString__EntityName);
		o_StringCache.f_AddConstantString(gc_ConstString__FileName);
		o_StringCache.f_AddConstantString(gc_ConstString__FormatString);
		o_StringCache.f_AddConstantString(gc_ConstString__Identifier);
		o_StringCache.f_AddConstantString(gc_ConstString__Left);
		o_StringCache.f_AddConstantString(gc_ConstString__OutputFormat);
		o_StringCache.f_AddConstantString(gc_ConstString__ParseFormat);
		o_StringCache.f_AddConstantString(gc_ConstString__Path);
		o_StringCache.f_AddConstantString(gc_ConstString__Properties);
		o_StringCache.f_AddConstantString(gc_ConstString__Right);
		o_StringCache.f_AddConstantString(gc_ConstString__Source);
		o_StringCache.f_AddConstantString(gc_ConstString__String);
		o_StringCache.f_AddConstantString(gc_ConstString__StringToHash);
		o_StringCache.f_AddConstantString(gc_ConstString__StringToParse);
		o_StringCache.f_AddConstantString(gc_ConstString__ToReturn);
		o_StringCache.f_AddConstantString(gc_ConstString__Value);
		o_StringCache.f_AddConstantString(gc_ConstString__VariableToGetTypeFrom);
		o_StringCache.f_AddConstantString(gc_ConstString__Wildcard);
		o_StringCache.f_AddConstantString(gc_ConstString_p_Source);
		o_StringCache.f_AddConstantString(gc_ConstString_p_SwitchValues);
		o_StringCache.f_AddConstantString(gc_ConstString_p_Values);
		o_StringCache.f_AddConstantString(gc_ConstString_rfc1034);

		o_StringCache.f_AddConstantString(gc_ConstString__24);
		o_StringCache.f_AddConstantString(gc_ConstString__25);
		o_StringCache.f_AddConstantString(gc_ConstString__27);
		o_StringCache.f_AddConstantString(gc_ConstString__28);
		o_StringCache.f_AddConstantString(gc_ConstString__29);
		o_StringCache.f_AddConstantString(gc_ConstString__2A);
		o_StringCache.f_AddConstantString(gc_ConstString__3B);
		o_StringCache.f_AddConstantString(gc_ConstString__3F);
		o_StringCache.f_AddConstantString(gc_ConstString__40);
		o_StringCache.f_AddConstantString(gc_ConstString____DS_Store);
		o_StringCache.f_AddConstantString(gc_ConstString_AlphaNum);
		o_StringCache.f_AddConstantString(gc_ConstString_Bare);
		o_StringCache.f_AddConstantString(gc_ConstString_Classes);
		o_StringCache.f_AddConstantString(gc_ConstString_Contributing_to_value);
		o_StringCache.f_AddConstantString(gc_ConstString_CurrentUser);
		o_StringCache.f_AddConstantString(gc_ConstString_LocalMachine);
		o_StringCache.f_AddConstantString(gc_ConstString_Parent);
		o_StringCache.f_AddConstantString(gc_ConstString_Reconcile);
		o_StringCache.f_AddConstantString(gc_ConstString_ReconcileForce);
		o_StringCache.f_AddConstantString(gc_ConstString_ReconcileNoOptions);
		o_StringCache.f_AddConstantString(gc_ConstString_ReconcileRemoved);
		o_StringCache.f_AddConstantString(gc_ConstString_RepoBranch);
		o_StringCache.f_AddConstantString(gc_ConstString_RepoName);
		o_StringCache.f_AddConstantString(gc_ConstString_RepoOnlyChanged);
		o_StringCache.f_AddConstantString(gc_ConstString_RepoTags);
		o_StringCache.f_AddConstantString(gc_ConstString_RepoType);
		o_StringCache.f_AddConstantString(gc_ConstString_Return);
		o_StringCache.f_AddConstantString(gc_ConstString_TraceCondition);
		o_StringCache.f_AddConstantString(gc_ConstString_TraceEval);
		o_StringCache.f_AddConstantString(gc_ConstString_TraceEvalSuccess);
		o_StringCache.f_AddConstantString(gc_ConstString_Win64_Classes);
		o_StringCache.f_AddConstantString(gc_ConstString_Win64_CurrentUser);
		o_StringCache.f_AddConstantString(gc_ConstString_Win64_LocalMachine);
		o_StringCache.f_AddConstantString(gc_ConstString__ArrayToExplode);
		o_StringCache.f_AddConstantString(gc_ConstString__ArrayToSearch);
		o_StringCache.f_AddConstantString(gc_ConstString__IndentString);
		o_StringCache.f_AddConstantString(gc_ConstString__JoinBy);
		o_StringCache.f_AddConstantString(gc_ConstString__ElementToFind);
		o_StringCache.f_AddConstantString(gc_ConstString__Base);
		o_StringCache.f_AddConstantString(gc_ConstString__Boolean);
		o_StringCache.f_AddConstantString(gc_ConstString__Default);
		o_StringCache.f_AddConstantString(gc_ConstString__EJSON);
		o_StringCache.f_AddConstantString(gc_ConstString__EntityType);
		o_StringCache.f_AddConstantString(gc_ConstString__Error);
		o_StringCache.f_AddConstantString(gc_ConstString__ExcludeWildcards);
		o_StringCache.f_AddConstantString(gc_ConstString__Executable);
		o_StringCache.f_AddConstantString(gc_ConstString__ExplodeFunction);
		o_StringCache.f_AddConstantString(gc_ConstString__Format);
		o_StringCache.f_AddConstantString(gc_ConstString__Inputs);
		o_StringCache.f_AddConstantString(gc_ConstString__JSON);
		o_StringCache.f_AddConstantString(gc_ConstString__Key);
		o_StringCache.f_AddConstantString(gc_ConstString__Length);
		o_StringCache.f_AddConstantString(gc_ConstString__Member);
		o_StringCache.f_AddConstantString(gc_ConstString__NumPaths);
		o_StringCache.f_AddConstantString(gc_ConstString__Positions);
		o_StringCache.f_AddConstantString(gc_ConstString__Property);
		o_StringCache.f_AddConstantString(gc_ConstString__PropertyType);
		o_StringCache.f_AddConstantString(gc_ConstString__ReplaceWith);
		o_StringCache.f_AddConstantString(gc_ConstString__ReplaceWithString);
		o_StringCache.f_AddConstantString(gc_ConstString__Root);
		o_StringCache.f_AddConstantString(gc_ConstString__SearchFor);
		o_StringCache.f_AddConstantString(gc_ConstString__SearchForCharacters);
		o_StringCache.f_AddConstantString(gc_ConstString__SplitBy);
		o_StringCache.f_AddConstantString(gc_ConstString__StateFile);
		o_StringCache.f_AddConstantString(gc_ConstString__StringToFind);
		o_StringCache.f_AddConstantString(gc_ConstString__StringToRemove);
		o_StringCache.f_AddConstantString(gc_ConstString__Strings);
		o_StringCache.f_AddConstantString(gc_ConstString__Time);
		o_StringCache.f_AddConstantString(gc_ConstString__Type);
		o_StringCache.f_AddConstantString(gc_ConstString__ValueName);
		o_StringCache.f_AddConstantString(gc_ConstString__WildcardToSearchFor);
		o_StringCache.f_AddConstantString(gc_ConstString__bFile);
		o_StringCache.f_AddConstantString(gc_ConstString_auto);
		o_StringCache.f_AddConstantString(gc_ConstString_bash);
		o_StringCache.f_AddConstantString(gc_ConstString_delete);
		o_StringCache.f_AddConstantString(gc_ConstString_leave);
		o_StringCache.f_AddConstantString(gc_ConstString_p_ErrorValues);
		o_StringCache.f_AddConstantString(gc_ConstString_p_LogValues);
		o_StringCache.f_AddConstantString(gc_ConstString_p_Params);
		o_StringCache.f_AddConstantString(gc_ConstString_p_Paths);
		o_StringCache.f_AddConstantString(gc_ConstString_p_ToConcat);
		o_StringCache.f_AddConstantString(gc_ConstString_p_Types);
		o_StringCache.f_AddConstantString(gc_ConstString_rebase);
		o_StringCache.f_AddConstantString(gc_ConstString_reset);
		o_StringCache.f_AddConstantString(gc_ConstString_OptionalChaining);
		o_StringCache.f_AddConstantString(gc_ConstString_Accessor);

		o_StringCache.f_AddConstantString(gc_ConstString_Symbol_Inherit);
	}
}
